

POST https://arliving.herokuapp.com/arliving/pb_create_order
content-type: application/json

{
    "restaurant_id":1,
    "order":[
        {"table":6, "name":"Pasta carbonara", "size":"small"},
        {"table":6, "name":"Pasta bolognese", "size":"big"}
    ]
}