


POST https://arliving.herokuapp.com/arliving/pb_create_order
content-type: application/json

{
    "restaurant_id":1,
    "orders":[
        {"table":15, "quantity":1, "size":"small", "name":"Pasta brt"},
        {"table":15, "quantity":2, "size":"big", "name":"Pizza carbonara"}
    ]
}



